name: GitHub Branch Protection check by complyctl

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  call_reusable_github_bp:
    name: GitHub Branch Protection Scan
    uses: AlexXuan233/org-infra/.github/workflows/reusable_github_bp.yml@add-github-bp-workflow
    with:
      target_github_repo: ${{ github.repository }}
      target_branch: master
    secrets:
      source_token: ${{ secrets.GITHUB_TOKEN }}